name: diyar_express
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.13
  flutter_launcher_icons: ^0.13.1
  flutter_bloc: ^8.1.4
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10+1
  equatable: ^2.0.5
  cached_network_image: ^3.3.1
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  bloc: ^8.1.3
  meta: ^1.11.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  auto_route: ^7.9.0
  dio: ^5.4.1
  jwt_decoder: ^2.0.1
  email_validator: ^2.1.17
  internet_connection_checker_plus: ^2.2.0
  dartz: ^0.10.1
  get_it: ^7.6.7
  url_launcher: ^6.2.5
  mask_text_input_formatter: ^2.9.0
  geolocator: ^11.0.0
  permission_handler: ^11.3.1
  yandex_mapkit: ^4.0.0
  easy_stepper: ^0.8.3
  cloud_firestore: ^4.15.9
  flutter_polyline_points: ^2.0.0

  easy_debounce: ^2.0.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter_native_splash:
  color: "#ffa462"
  image: "assets/images/app_logo.png"
  android: true
  ios: true

  android_12:
    image: assets/images/app_logo.png
    color: "#ffa462"
